/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#ffddb8",
        "secondary": "#006d42",
        "tertiary-fixed-dim": "#ffb95f",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6d0",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed": "#d7e3ff",
        "surface": "#f8f9fa",
        "secondary-container": "#9af6be",
        "tertiary-container": "#573500",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a3c6e",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#7ed9a3",
        "on-primary-fixed-variant": "#264679",
        "surface-container-low": "#f3f4f5",
        "on-primary-container": "#8aa8e0",
        "error": "#ba1a1a",
        "secondary-fixed": "#9af6be",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#005230",
        "primary-fixed-dim": "#abc7ff",
        "outline": "#747780",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        "on-secondary-container": "#087347",
        "on-secondary-fixed": "#002110",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-primary": "#abc7ff",
        "tertiary": "#3a2100",
        "surface-tint": "#405e92",
        "primary": "#002653",
        "on-tertiary-container": "#e89500",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed": "#001b3f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xs": "8px",
        "xl": "32px",
        "md": "16px",
        "margin-mobile": "16px",
        "tap-target-min": "44px",
        "gutter-mobile": "12px",
        "sm": "12px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
